# Generated by Django 6.0.1 on 2026-01-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_rename_borrowing_id_payment_borrowing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
