# Generated by Django 6.0.1 on 2026-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_payment_borrowing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(choices=[("PENDING", "Pending"), ("PAID", "Paid")]),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(choices=[("PAYMENT", "Payment"), ("FINE", "Fine")]),
        ),
    ]
