# Generated by Django 6.0.1 on 2026-01-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_payment_status_alter_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("CANCELED", "Canceled"),
                ]
            ),
        ),
    ]
