# Generated by Django 6.0.1 on 2026-01-23 15:57

import borrowings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="expected_return_date",
            field=models.DateField(validators=[borrowings.models.validate_date]),
        ),
    ]
